spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8889/realms/elearning
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:8432/elearning_db
    driver-class-name: org.postgresql.Driver
    username: m1usr
    password: qwerqwer
  application:
    name: elearning-a01-m1
server:
  port: 8888
keycloak:
  server-url: http://localhost:8889
  client-id: spring-boot-elearning
  client-secret: Swf1heYpE03N3XeuJJvaJWTpO2b9Zaqp
  realm: master
  target-realm: elearning
