
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/istad-oauth2
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/db_elearning_a01_m1
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwer
  application:
    name: elearning-a01-m1
server:
  port: 8888
